Updated to LÖVE 11.1
BytewaveMLP/BrainLOVE pull request #3
Opened 2018-06-06 08:20 UTC by suttonwilliamd

With the latest version of LÖVE, colors were changed to 0-1 range instead of 0-255.  This commit makes BrainLOVE visible again!

2018-06-06 15:44 UTC, BytewaveMLP requested changes
Missed a couple of 0-255 -> 0-1 scale conversions, but otherwise LGTM.

(kind of annoyed that LÖVE changed this in their stdlib, but maybe it was better for color math or something)

2018-06-06 15:44 UTC, BytewaveMLP commented on main.moon
> +				runButton\setColor 0.49, 200, 0.49
`200`  should be `0.78`, keeping with the trend here

2018-06-06 15:44 UTC, BytewaveMLP commented on main.moon
> +				runButton\setColor 200, 0.49, 0.49
Here too

2018-06-06 16:11 UTC, suttonwilliamd commented
I wasn't sure how many decimal places were useful with the color data.  My math says 175 should be 0.686~ I only used 0.49 for 125 because it came out to 0.49019~.  My question is, should I change my 0.686's to just 0.68's while I'm fixing this thing you pointed out, or change the 200's to 0.784?

Thanks!

2018-06-06 17:51 UTC, BytewaveMLP commented
My math training would tell me to use `0.490`, just to make it clear we're working at 3 decimal places everywhere.

Otherwise, LGTM.

~~I really ought to get back and finish this project at some point, but text input has had me stuck for a while. :p~~

2018-06-07 02:38 UTC, BytewaveMLP approved these changes

2018-06-07 02:39 UTC, merged